Found cached dataset json (/home/st-aleksandr-razin/.cache/huggingface/datasets/RazinAleks___json/RazinAleks--SO-Python_QA-Data_Science_and_Machine_Learning_class-81f83bcd8b3cf0a9/0.0.0/8bb11242116d547c741b2e8a1f18598ffdd40a1d4f2a2872c7a28b697434bc96)
Loading cached processed dataset at /home/st-aleksandr-razin/.cache/huggingface/datasets/RazinAleks___json/RazinAleks--SO-Python_QA-Data_Science_and_Machine_Learning_class-81f83bcd8b3cf0a9/0.0.0/8bb11242116d547c741b2e8a1f18598ffdd40a1d4f2a2872c7a28b697434bc96/cache-5d734272de693c1c.arrow




  7%|████████████▋                                                                                                                                                                     | 4/56 [13:12<2:51:46, 198.20s/it]
Traceback (most recent call last):
  File "/home/st-aleksandr-razin/workspace/SRC_QC4QA/QA_pipeline/scripts/test_script.py", line 99, in <module>
    main()
  File "/home/st-aleksandr-razin/.conda/envs/qc4qa/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/st-aleksandr-razin/.conda/envs/qc4qa/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/st-aleksandr-razin/.conda/envs/qc4qa/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/st-aleksandr-razin/.conda/envs/qc4qa/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/st-aleksandr-razin/workspace/SRC_QC4QA/QA_pipeline/scripts/test_script.py", line 83, in main
    eval_model(
  File "/home/st-aleksandr-razin/workspace/SRC_QC4QA/QA_pipeline/models/test_model.py", line 160, in eval_model
    log_results(results, log_config, run)
  File "/home/st-aleksandr-razin/workspace/SRC_QC4QA/QA_pipeline/models/test_model.py", line 86, in log_results
    save_csv(results, f"{log_config['dir']}/{log_config['file_name']}")
KeyError: 'file_name'